<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SizingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('global_settings')->upsert([
            ['key' => 'eru_cost_usd', 'value' => '14000', 'description' => 'Elastic Resource Unit (64GB RAM) annual subscription cost in USD', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'ram_per_eru_gb', 'value' => '64', 'description' => 'Memory per ERU license constant (GB)', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'index_expansion_factor', 'value' => '1.25', 'description' => 'Index metadata expansion factor (1.25x default)', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'usd_to_eur_rate', 'value' => '0.92', 'description' => 'USD to EUR conversion rate', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'usd_to_tnd_rate', 'value' => '3.10', 'description' => 'USD to TND conversion rate', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'ai_provider', 'value' => 'ollama', 'description' => 'Active AI provider (ollama, lmstudio, gemini, openrouter)', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'ollama_model', 'value' => 'gemma4:e2b', 'description' => 'Ollama active model name', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'ollama_url', 'value' => 'http://localhost:11434', 'description' => 'Ollama API endpoint URL', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'lmstudio_model', 'value' => 'qwen2.5-coder-7b-instruct', 'description' => 'LM Studio active model name', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'lmstudio_url', 'value' => 'http://localhost:1234/v1', 'description' => 'LM Studio API endpoint URL', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'gemini_model', 'value' => 'gemini-1.5-flash', 'description' => 'Gemini active model name', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'gemini_api_key', 'value' => '', 'description' => 'Gemini API Key', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'openrouter_model', 'value' => 'meta-llama/llama-3-8b-instruct:free', 'description' => 'OpenRouter active model name', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'openrouter_api_key', 'value' => '', 'description' => 'OpenRouter API Key', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'elastic_cloud_monthly_cost_per_gb_ram', 'value' => '45.0000', 'description' => 'Elastic Cloud monthly cost per GB RAM in USD', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'siem_agent_monthly_cost_per_device', 'value' => '15.0000', 'description' => 'SIEM agent monthly cost per device in USD', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'mdr_agent_monthly_cost_per_device', 'value' => '30.0000', 'description' => 'MDR agent monthly cost per device in USD', 'created_at' => now(), 'updated_at' => now()],
            ['key' => 'edr_agent_monthly_cost_per_device', 'value' => '10.0000', 'description' => 'EDR agent monthly cost per device in USD', 'created_at' => now(), 'updated_at' => now()],
        ], ['key']);

        // 2. Seed Asset Types
        DB::table('asset_types')->upsert([
            [
                'id' => 1,
                'name' => 'Active Directory',
                'avg_event_size_bytes' => 1200,
                'calibration_mode' => 'monthly_gb_per_device',
                'runs_siem_agent' => true,
                'runs_mdr_agent' => false,
                'runs_edr_agent' => false,
                'min_eps_default' => 2.89,
                'avg_eps_default' => 12.88,
                'max_eps_default' => 28.94,
                'max_monthly_gb_default' => 90,
                'description' => 'Primary identity and directory domain controllers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'FortiGate Firewalls',
                'avg_event_size_bytes' => 600,
                'calibration_mode' => 'monthly_gb_per_device',
                'runs_siem_agent' => true,
                'runs_mdr_agent' => true,
                'runs_edr_agent' => false,
                'min_eps_default' => 9.65,
                'avg_eps_default' => 32.12,
                'max_eps_default' => 77.16,
                'max_monthly_gb_default' => 120,
                'description' => 'Perimeter firewalls and boundary traffic logging',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'EDR / XDR Integration',
                'avg_event_size_bytes' => 1000,
                'calibration_mode' => 'monthly_gb_total',
                'runs_siem_agent' => false,
                'runs_mdr_agent' => true,
                'runs_edr_agent' => false,
                'min_eps_default' => 0.0077,
                'avg_eps_default' => 0.031,
                'max_eps_default' => 0.077,
                'max_monthly_gb_default' => 30,
                'description' => 'Third-party EDR/XDR integration (SentinelOne, Defender, etc.) over 150 endpoints - avoiding native Elastic Defend XDR deployment to save client costs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Windows Servers',
                'avg_event_size_bytes' => 800,
                'calibration_mode' => 'eps_per_device',
                'runs_siem_agent' => true,
                'runs_mdr_agent' => false,
                'runs_edr_agent' => true,
                'min_eps_default' => 1.00,
                'avg_eps_default' => 8.00,
                'max_eps_default' => 30.00,
                'max_monthly_gb_default' => null,
                'description' => 'Windows Server operating system event logs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Linux Servers',
                'avg_event_size_bytes' => 500,
                'calibration_mode' => 'eps_per_device',
                'runs_siem_agent' => true,
                'runs_mdr_agent' => false,
                'runs_edr_agent' => true,
                'min_eps_default' => 0.50,
                'avg_eps_default' => 3.00,
                'max_eps_default' => 15.00,
                'max_monthly_gb_default' => null,
                'description' => 'Linux system logging (syslog, auth.log, auditd)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Network Switches',
                'avg_event_size_bytes' => 250,
                'calibration_mode' => 'eps_per_device',
                'runs_siem_agent' => true,
                'runs_mdr_agent' => true,
                'runs_edr_agent' => false,
                'min_eps_default' => 0.10,
                'avg_eps_default' => 2.00,
                'max_eps_default' => 15.00,
                'max_monthly_gb_default' => null,
                'description' => 'Core switch system telemetry and network configurations',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id']);

        // 3. Seed Scenarios
        DB::table('scenarios')->upsert([
            [
                'id' => 1,
                'name' => 'Scenario 1',
                'description' => 'Minimum Ingest, Hot-Only (Short Retention)',
                'workload_profile' => 'min',
                'retention_days' => 7,
                'hot_days' => 7,
                'warm_days' => 0,
                'cold_days' => 0,
                'frozen_days' => 0,
                'hot_replicas' => 1,
                'warm_replicas' => 1,
                'cold_replicas' => 0,
                'frozen_replicas' => 0,
                'is_system_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Scenario 2',
                'description' => 'Minimum Ingest, Multi-Tier (Long Retention)',
                'workload_profile' => 'min',
                'retention_days' => 365,
                'hot_days' => 30,
                'warm_days' => 0,
                'cold_days' => 335,
                'frozen_days' => 0,
                'hot_replicas' => 1,
                'warm_replicas' => 1,
                'cold_replicas' => 0,
                'frozen_replicas' => 0,
                'is_system_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Scenario 3',
                'description' => 'Average Ingest, Hot-Only (Standard Retention)',
                'workload_profile' => 'avg',
                'retention_days' => 30,
                'hot_days' => 30,
                'warm_days' => 0,
                'cold_days' => 0,
                'frozen_days' => 0,
                'hot_replicas' => 1,
                'warm_replicas' => 1,
                'cold_replicas' => 0,
                'frozen_replicas' => 0,
                'is_system_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Scenario 4',
                'description' => 'Average Ingest, Multi-Tier (Long Retention)',
                'workload_profile' => 'avg',
                'retention_days' => 365,
                'hot_days' => 7,
                'warm_days' => 23,
                'cold_days' => 60,
                'frozen_days' => 275,
                'hot_replicas' => 1,
                'warm_replicas' => 1,
                'cold_replicas' => 0,
                'frozen_replicas' => 0,
                'is_system_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Scenario 5',
                'description' => 'Maximum Ingest, Hot + Warm (Medium Retention)',
                'workload_profile' => 'max',
                'retention_days' => 90,
                'hot_days' => 14,
                'warm_days' => 76,
                'cold_days' => 0,
                'frozen_days' => 0,
                'hot_replicas' => 1,
                'warm_replicas' => 1,
                'cold_replicas' => 0,
                'frozen_replicas' => 0,
                'is_system_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Scenario 6',
                'description' => 'Maximum Ingest, Multi-Tier (Long Retention)',
                'workload_profile' => 'max',
                'retention_days' => 365,
                'hot_days' => 7,
                'warm_days' => 23,
                'cold_days' => 60,
                'frozen_days' => 275,
                'hot_replicas' => 1,
                'warm_replicas' => 1,
                'cold_replicas' => 0,
                'frozen_replicas' => 0,
                'is_system_default' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['id']);
    }
}
